### ISSUE TITLE
Docu for SML needs to be changed

### ISSUE THREAD

**Issue by Kurisutian** [alengwenus/esphome_components#1]
Hi!

I just noticed that only the code examples in the documentation for SML were adjusted by replacing 'obis' with 'obis_code' but the description of the existing options in the text still has 'obis' as an option. It should also be replaced with 'obis_code'.
Thanks for offering this component, it's working flawless so far!

**Comment by alengwenus** [comment]
Thanks @Kurisutian. Fixed it.
