### ISSUE TITLE
PIN submission

### ISSUE THREAD

**Issue by veitw** [alengwenus/esphome_components#4]
Hi @alengwenus,

thank you very much for your effort. The sml component works great for me.

Do you plan to add support for sending a PIN to the meter?

I use a Holley DTZ541, unfortunately it emits only very basic OBIS data unless a PIN is submitted:
- active power
- inbound power meter tariff 1
- inbound power meter tariff 2
- inbound power meter combined
- outbound power meter

But after a PIN is supplied, it will send these additional values:
- voltage L1
- voltage L2
- voltage L3
- current L1
- current L2
- current L3
- voltage phase angle L2:L1
- voltage phase angle L3:L2
- voltage phase angle L1:L3
- current phase angle L2:L1
- current phase angle L3:L2
- current phase angle L1:L3
- mains frequency

Best regards,
// Veit

**Comment by alengwenus** [comment]
All energy meters I know have a button or can be flashed using a torch to enter the PIN.
Doesn't that work with your energy meter?

**Comment by veitw** [comment]
It has one, it also shows the extended values on the display screen after entering the PIN.

But after a minute or so, it returns to the basic values and one has to re-enter the PIN. Thus the question whether you plan extend the component to submit the PIN to the smart meter.

**Comment by BMOD89** [comment]
I have checked the manual of your meter. There is the possibility to disable the pin retrieval. With that option you should be able to continuously see all values.

**Comment by veitw** [comment]
This is what I had already configured:
* Pin off
* Info on

It gave me only the information described above.

@BMOD89: Do you have a real manual for this device? So far I only found some very basic guides, mostly like quick start guides for the menu.

**Comment by BMOD89** [comment]
I guess it is the same manual: https://www.holleytech.de/wp-content/uploads/2021/03/Benutzerhandbuch_mME-DTZ541_V2.0.pdf  

I have a different meter, but the principle (menu and so on) is similar and for my meter it is sufficient to set the values as you just described.  

I am not 100% sure but I think the optical interface is only unidirectional. So you cannot set a pin via the optical interface. At least I haven't read about that possibility yet...

**Comment by veitw** [comment]
@BMOD89: Thank you very much. From this document I learned that, differing from the quick start guide, the power meter does not have two but three different modes for the D0 interface; "reduced", "complete" and "manufacturer-specific" data set -- and the additional information I'd like to monitor, which was said to be available in the quick start guide, is only transmitted in the manufacturer-specific mode.

Regarding to the manual, this mode can be enabled via the "rear interface" -- whatever that exactly means, as it is nowhere mentioned again in the manual...
