### ISSUE TITLE
Example for Wemos D1 mini?

### ISSUE THREAD

**Issue by kayloehmann** [alengwenus/esphome_components#7]
Hi there,

thanks for the great work! Could you please share your hardware setup based on the Wemos D1 mini, especially PIN selection? 
I have put together hardware based on homeassistant glow, but cannot retrieve any values.

Kay.

**Comment by alengwenus** [comment]
I bought one of these sensors: https://www.ebay.de/itm/ttl-ir-lesekopf-lese-schreib-Kopf-EHZ-Volkszahler-Hichi-Smartmeter/313460034498
I connected it to GPIO1 (TX) and GPIO3 (RX). But I had to switch the logger to UART1.
Actually any sufficient IR sensor should do. Maybe you have to play around with the internal pull-up/pull-down resistors?

**Comment by kayloehmann** [comment]
I got it working by adding a fourth pin, also using UART1. Thx. :-)
![zaehler](https://user-images.githubusercontent.com/34281638/154836235-10eb5c36-265c-48d4-9f0a-42b5570e0fde.jpg)
